### PR TITLE
Add vistaio and xmedcon ebuild to Booboo for amide

### PR DESCRIPTION
**Pull request by gerddie**
These are two additional libraries that can be used by amide. Hence: I'd like to add them to your repo,  before I move amide and ginkgocadx to sci-visualization. Related: #15

### CODE REVIEW

**Comment by l29ah** [comment]
Your commit doesn't respect https://github.com/l29ah/booboo/blob/master/metadata/layout.conf#L3
Also, this is not CVS, so don't put those funny ChangeLog files in plz.
Also, there are already xmedcon and vistaion in ::imaging that belongs to sci-libs, so i'd prefer your updated one to belong there as well. Or even residing in that repo; why do you want them there in the first place?

**Comment by gerddie** [comment]
* 1st corrected. 
* Changelogs are part of the [workflow](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Common_ebuild_work), i.e.  *repoman commit* creates and commits these automatically. I can, of course, remove these files, and use *git commit* if you prefer. 
* Well, I wouldn't mind if they are only in ::imaging, but how do I tell people that they need yet another overlay to get these dependencies?  Also *repoman* was complaining about missing dependencies,  even though this overlay is installed on my machine, so as an workaround I thought of adding these ebuilds.

**Comment by l29ah** [comment]
On Thu, Mar 24, 2016 at 05:37:23AM -0700, Gert Wollny wrote:
> * Changelogs are part of the [workflow](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Common_ebuild_work), i.e.  *repoman commit* creates and commits these automatically. I can, of course, remove these files, and use *git commit* if you prefer. 

Well, i don't observe this stuff in the main tree git, so i suspect some misconfiguration on your side.

> * Well, I wouldn't mind if they are only in ::imaging, but how do I tell people that they need yet another overlay to get these dependencies?  Also *repoman* was complaining about missing dependencies,  even though this overlay is installed on my machine, so as an workaround I thought of adding these ebuilds.  

You don't. Paludis or eix(?) does this for you. I have lots of deps being pulled from other repos and no one have complained yet afaik.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by gerddie** [comment]
* Regarding the Changelogs, if you don't want them, then you should add *update-changelog = false* to your layout file. 
* *eix* and *emerge* only recognize the overlays that are actually installed, I'd guess that *paludis* is not different. Well, Somehow I suspect that people just search from where they can get the missing e-builds ... 

Anyway, if you say you don't want these e-builds in this overlay, then I just close this pull request.

**Comment by l29ah** [comment]
On Thu, Mar 24, 2016 at 06:01:21AM -0700, Gert Wollny wrote:
> * Regarding the Changelogs, if you don't want them, then you should add *update-changelog = false* to your layout file. 

Will do, thanks.

> * *eix* and *emerge* only recognize the overlays that are actually installed, I'd guess that *paludis* is not different. Well, Somehow I suspect that people just search from where they can get the missing e-builds ... 

eix and paludis can search using an index of all the layman (and some others, in case of paludis) packages.

> Anyway, if you say you don't want these e-builds in this overlay, then I just close this pull request. 

ok

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Pull request closed without merging**
