### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Pastafarianist**

### CODE REVIEW

**Comment by l29ah** [comment]
:*
Actually, the ebuild is obsolete as openbazaar have split their repos, but the deps are quite troublesome, especially pynacl.

**Comment by Pastafarianist** [comment]
I suppose the previous repository contained the code for both the client and the server, so merely changing the git url won't probably work. Can you estimate how much work will have to be done to fix the ebuild?

**Comment by l29ah** [comment]
It must be easy and it might be that i've already done it, but i have no way to test it until i figure out how to build pynacl properly; see also https://github.com/pyca/pynacl/issues/145

**Comment by Pastafarianist** [comment]
Why not do `/tmp/pynacl/build/temp.linux-x86_64-2.7` ?

**Comment by l29ah** [comment]
I don't understand what do you suggest.

**Comment by Pastafarianist** [comment]
If re-building pynacl fails because of some temporary directory, why not just delete it?

**Comment by l29ah** [comment]
On Wed, Oct 07, 2015 at 03:33:00PM -0700, Pastafarianist wrote:
> If re-building pynacl fails because of some temporary directory, why not just delete it?

Because the problem is not that it's being rebuilt, but that distutils-r1 installs python stuff by doing two calls to setup.py instead of just one, and i assume it needs the results of the previous build process. According to the pynacl sources they're doing some hacky stuff with the build process, but i'm not a python developer so i don't know what's the proper way to solve this. If you have an idea about building it, i'll accept the resulting ebuild (:

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Pastafarianist** [comment]
But since this ebuild exists, it probably worked with an older version of pynacl? Is it possible to use that one?

**Comment by l29ah** [comment]
On Wed, Oct 07, 2015 at 04:19:25PM -0700, Pastafarianist wrote:
> But since this ebuild exists, it probably worked with an older version of pynacl? Is it possible to use that one?

It wasn't depending on pynacl.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Pastafarianist** [comment]
Okay, so let me make this straight: at one point the original repo contained code which did not depend on pynacl. This ebuild was created at that time. Then the repo was updated, but this ebuild wasn't, right?

**Comment by l29ah** [comment]
On Wed, Oct 07, 2015 at 04:30:26PM -0700, Pastafarianist wrote:
> Okay, so let me make this straight: at one point the original repo contained code which did not depend on pynacl. This ebuild was created at that time. Then the repo was updated, but this ebuild wasn't, right?

The repo's README states it's obsolete and is no longer updated. The ebuild is up to date with the repo.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Pastafarianist** [comment]
I mean that the code in openbazaar-server & openbazaar-client uses pynacl, but when it was in the old repo, it didn't. Okay, thanks.

**Comment by l29ah** [comment]
Okay, i've figured out the deps but don't understand how am i supposed to install it into a system.

**Pull request merged**
