### PR TITLE
conky: added xdamage flag

### PR DESCRIPTION
**Pull request by andrey-smirnov**
Modified original conky ebuild to add xdamage flag to be able to build conky without it.

### CODE REVIEW

**Comment by l29ah** [comment]
Чё несвежий такой?

**Comment by gordon-quad** [comment]
да похуй же, взял из портежа. Мне флажок нужен только.

**Comment by l29ah** [comment]
On Sun, Oct 23, 2016 at 04:26:36AM -0700, gordon-quad wrote:
> да похуй же, взял из портежа. Мне флажок нужен только.

В портеже новее.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
On Fri, Oct 21, 2016 at 06:56:40AM -0700, andrey-smirnov wrote:
> Modified original conky ebuild to add xdamage flag to be able to build conky without it.

Чё такой несвежий?

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Pull request merged**
