### PR TITLE
+ new ebuild: sys-fs/nullfs

### PR DESCRIPTION
**Pull request by gordon-quad**
some stuff

### CODE REVIEW

**Comment by l29ah** [comment]
Ask your editor to highlight trailing spaces ;)

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
Why are you using a fork instead of the original repo?

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by gordon-quad** [comment]
Oops, sorry for spaces. Fixed.
>Why are you using a fork instead of the original repo?

Standard github workflow? Push stuff to private repo and then PR, am I doing something wrong?

**Comment by gordon-quad** [comment]
Oh, you mean the actual nullfs. Fork made nulnfs work but in original repo it crashes.

**Comment by gordon-quad** [comment]
actually you're right, fuck it

**Pull request closed without merging**
